organization_index:
    path:     /
    defaults: { _controller: "UserBundle:Organization:index" }
    methods:  GET

organization_show:
    path:     /{id}/show
    defaults: { _controller: "UserBundle:Organization:show" }
    methods:  GET

organization_new:
    path:     /new
    defaults: { _controller: "UserBundle:Organization:new" }
    methods:  [GET, POST]

organization_edit:
    path:     /{id}/edit
    defaults: { _controller: "UserBundle:Organization:edit" }
    methods:  [GET, POST]

organization_delete:
    path:     /{id}/delete
    defaults: { _controller: "UserBundle:Organization:delete" }
    methods:  DELETE
