user_index:
    path:     /admin/
    defaults: { _controller: "UserBundle:Customer:index" }
    methods:  GET

user_show:
    path:     /admin/{id}/show
    defaults: { _controller: "UserBundle:Customer:show" }
    methods:  GET

user_new:
    path:     /new
    defaults: { _controller: "UserBundle:Customer:new" }
    methods:  [GET, POST]

user_edit:
    path:     /{id}/edit
    defaults: { _controller: "UserBundle:Customer:edit" }
    methods:  [GET, POST]

user_delete:
    path:     /{id}/delete
    defaults: { _controller: "UserBundle:Customer:delete" }
    methods:  DELETE
