<?php

namespace AppBundle\Repository;

/**
 * AnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnswerRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAnswerOrderedByDate($ticket)
    {
        return $this->createQueryBuilder('answer')
            ->where('answer.ticket = :ticket')
            ->setParameter('ticket', $ticket)
            ->orderBy('answer.dateCreated', 'DESC')
            ->getQuery()
            ->execute()
            ;
    }
}
