<?php

namespace AppBundle\Repository;

use UserBundle\Entity\User;

/**
 * EntretienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntretienRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllEntretiensByInterviwee(User $user)
    {
        return $this->createQueryBuilder('entretien')
            ->where('entretien.interviewee = :user')
            ->setParameter('user', $user)
            ->getQuery()
            ->execute()
            ;
    }
}
