<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use UserBundle\Entity\User;

/**
 * EntretienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntretienRepository extends EntityRepository
{
    public function getAllEntretiensByInterviwee(User $user)
    {
        return $this->createQueryBuilder('entretien')
            ->where('entretien.young = :user')
            ->setParameter('user', $user)
            ->getQuery()
            ->execute()
            ;
    }

    public function getInterviewByGuestAndByYoung(User $user, User $young)
    {
        return $this->createQueryBuilder('entretien')
            ->leftJoin('entretien.interviewGuests', 'guest')
            ->addSelect('guest')
            ->where('guest.user = :user')
            ->setParameter('user', $user)
            ->andWhere('entretien.young = :young')
            ->setParameter('young', $young)
            ->getQuery()
            ->execute()
            ;
    }

    public function getInterviewsByAuthorAndAsGuest(User $user)
    {
        return $this->createQueryBuilder('entretien')
            ->where('entretien.author = :user')
            ->setParameter('user', $user)
            ->join('entretien.interviewGuests', 'guest')
            ->addSelect('guest')
            ->orWhere('guest.user = :user')
            ->setParameter('user', $user)
            ->orderBy('entretien.date', 'ASC')
            ->getQuery()
            ->execute()
            ;
    }
}
