<?php

namespace AppBundle\Repository;

/**
 * InterviewUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterviewUserRepository extends \Doctrine\ORM\EntityRepository
{
}
