<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use UserBundle\Entity\User;

/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends EntityRepository
{
    public function findTicketsByAuthor(User $user)
    {
        return $this->createQueryBuilder('ticket')
            ->where('ticket.statut = :statut')
            ->setParameter('statut', 1)
            ->andWhere('ticket.fromWho = :user')
            ->setParameter('user', $user)
            ;
    }

    public function getAllTicketsUserFromAndTo(User $user)
    {
        return $this->createQueryBuilder('ticket')
            ->where('ticket.fromWho = :user')
            ->setParameter('user', $user)
            ->orWhere('ticket.toWho = :user')
            ->setParameter('user', $user)
            ->getQuery()
            ->execute();
    }
}
