app.entretien:
    resource: "@AppBundle/Controller/EntretienController.php"
    type:     annotation
    prefix:   /dashboard

app.compterendu:
    resource: "@AppBundle/Controller/CompteRenduController.php"
    type:     annotation
    prefix:   /dashboard

app.documentation:
    resource: "@DocumentationBundle/Controller/"
    type:     annotation
    prefix:   /dashboard

app:
    resource: "@AppBundle/Controller/AppController.php"
    type:     annotation
    prefix:   /

app.event:
    resource: "@AppBundle/Controller/EventController.php"
    type:     annotation
    prefix:   /

app.reservation:
    resource: "@AppBundle/Controller/ReservationController.php"
    type:     annotation
    prefix:   /dashboard

app.ticket:
    resource: "@AppBundle/Controller/TicketController.php"
    type:     annotation
    prefix:   /dashboard

app.api.ticket:
    resource: "@AppBundle/Controller/ApiTicketController.php"
    type:     annotation
    prefix:   /dashboard

user.security:
    resource: "@UserBundle/Controller/SecurityController.php"
    type:     annotation
    prefix:   /

user:
    resource: "@UserBundle/Controller/UserController.php"
    type:     annotation
    prefix:   /dashboard

app.api.user:
    resource: "@UserBundle/Controller/ApiUserController.php"
    type:     annotation
    prefix:   /dashboard

app.answer:
    resource: "@AppBundle/Controller/ApiAnswerController.php"
    type:     annotation
    prefix:   /dashboard

app.interviewUser:
    resource: "@AppBundle/Controller/InterviewUserController.php"
    type:     annotation
    prefix:   /dashboard

blog:
    resource: "@BlogBundle/Controller/"
    type:     annotation
    prefix:   /

blog_billet:
    resource: "@BlogBundle/Controller/BilletController.php"
    type:     annotation
    prefix:   /blog

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"