app:
    resource: "@AppBundle/Controller/AppController.php"
    type:     annotation
    prefix:   /

app.action:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /admin

user.security:
    resource: "@UserBundle/Controller/SecurityController.php"
    type:     annotation
    prefix: /

user:
    resource: "@UserBundle/Controller/UserController.php"
    type:     annotation
    prefix:   /admin

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"