app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /member

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"