app_entretien:
    resource: "@AppBundle/Controller/EntretienController.php"
    type:     annotation
    prefix:   /

app.documentation:
    resource: "@DocumentationBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/AppController.php"
    type:     annotation
    prefix:   /

app.event:
    resource: "@AppBundle/Controller/EventController.php"
    type:     annotation
    prefix:   /

app.reservation:
    resource: "@AppBundle/Controller/ReservationController.php"
    type:     annotation
    prefix:   /admin

app.ticket:
    resource: "@AppBundle/Controller/TicketController.php"
    type:     annotation
    prefix:   /admin

user.security:
    resource: "@UserBundle/Controller/SecurityController.php"
    type:     annotation
    prefix: /

user:
    resource: "@UserBundle/Controller/UserController.php"
    type:     annotation
    prefix:   /admin


fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"