# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.form.registration:
        class: UserBundle\Form\CredentialType
        tags:
            - { name: form.type, alias: app_user_registration }
    find.orga:
        class: UserBundle\Twig\FindOrga
        arguments:
            doctrine:  '@doctrine'
        tags:
          - { name: twig.extension }

    find.member:
        class: UserBundle\Twig\FindMember
        arguments:
            doctrine:  '@doctrine'
        tags:
          - { name: twig.extension }
