# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:

services:

    app.flash_message:
        class: AppBundle\EventListener\FlashMessage
        autowire: true
        tags:
          - { name: doctrine.event_subscriber }

    app.security.login_form_authenticator:
        class: UserBundle\Security\LoginFormAuthenticator
        autowire: true

    app.doctrine.hash_password_listener:
        class: UserBundle\DoctrineEvent\HashPasswordListener
        autowire: true
        tags:
            - { name: doctrine.event_subscriber }

    app.user_voter:
        class: UserBundle\Security\UserVoter
        tags:
            - { name: security.voter }
        public: false
      #app.doctrineevent.mail_user:
       #     class: UserBundle\DoctrineEvent\MailUserListener
        #    autowire: true
         #   tags:
          #      - { name: doctrine.event_subscriber }

    app.form.youngster_coach:
        class:  AppBundle\Form\TicketType
        autowire: true
        tags:
            - { name: form.type }