# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:

services:

    app.flash_message:
        class: AppBundle\EventListener\FlashMessage
        autowire: true
        tags:
          - { name: doctrine.event_subscriber }

    app.security.login_form_authenticator:
        class: UserBundle\Security\LoginFormAuthenticator
        autowire: true

    app.doctrine.hash_password_listener:
        class: UserBundle\DoctrineEvent\HashPasswordListener
        autowire: true
        tags:
            - { name: doctrine.event_subscriber }

   # app.user_voter:
    #    class: UserBundle\Security\UserVoter
     #   tags:
      #      - { name: security.voter }
      #  public: false

# Envoie les mails aux différents coach
    app.doctrine.answer_mail_workflow:
        class: AppBundle\Doctrine\AnswerMailWorkflow
        autowire: true
        tags:
            - { name: doctrine.event_subscriber }

    app.doctrine.ticket_mail_workflow:
        class: AppBundle\Doctrine\TicketMailWorkflow
        autowire: true
        tags:
            - { name: doctrine.event_subscriber }

    app.form.youngster_coach:
        class:  AppBundle\Form\Type\TicketType
        autowire: true
        tags:
            - { name: form.type }

    app.doctrine.entretien_mail_workflow:
        class: AppBundle\Doctrine\EntretienMailWorkflow
        autowire: true
        tags:
            - { name: doctrine.event_subscriber }

    app.doctrine.status_mail_workflow:
        class: AppBundle\Doctrine\StatusMailWorkflow
        autowire: true
        tags:
            - { name: doctrine.event_subscriber }

    app.api_response:
        class: AppBundle\Service\ajaxResponse
        autowire: true
