<?php

namespace DocumentationBundle\Repository;

use Doctrine\ORM\EntityRepository;
use UserBundle\Entity\User;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends EntityRepository
{
    public function getCategoryDocumentByUserDisplayed(User $destinataire)
    {
        return $this->createQueryBuilder('categorie')
            ->leftJoin('categorie.documents', 'documents')
            ->addSelect('documents')
            ->where('documents.destinataire = :destinataire')
            ->setParameter('destinataire', $destinataire)
            ->getQuery()
            ->execute()
            ;
    }

    public function findOrderASCCategorie($user)
    {
        return $this->createQueryBuilder('categorie')
            ->where('categorie.owner is NULL or categorie.owner = :owner')
            ->setParameter('owner', $user)
            ->orderBy('categorie.name', 'ASC')
            ->getQuery()
            ->execute()
            ;
    }
}
