<?php

namespace DocumentationBundle\Repository;

use UserBundle\Entity\User;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCategoryDocumentByUserDisplayed(User $destinataire)
    {
        return $this->createQueryBuilder('categorie')
            ->leftJoin('categorie.documents', 'documents')
            ->addSelect('documents')
            ->where('documents.destinataire = :destinataire')
            ->setParameter('destinataire', $destinataire)
            ->getQuery()
            ->execute()
            ;
    }
}
