<?php

namespace UserBundle\Repository;

use Doctrine\Common\Collections\Criteria;
use Doctrine\ORM\EntityRepository;
use UserBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{


    /**
     * @return mixed
     */
    public function findUserNonAdmin()
    {
        return $this->createQueryBuilder('user')
            ->andWhere('user.role != :role')
            ->setParameter('role', 'ROLE_ADMIN')
            ->leftJoin('user.addresses', 'address')
            ->addSelect('address')
            ->leftJoin('user.phoneNumbers', 'phonenumber')
            ->addSelect('phonenumber')
            ->getQuery()
            ->execute();
    }

    public  function findYoungsterByCoach(User $user)
    {
        $qb = $this->createQueryBuilder('user')
            ->andWhere('user.role = :role ')
            ->setParameter('role', 'ROLE_YOUNGSTER')
            ->leftJoin('user.coach', 'coach')
            ->addSelect('coach')
            ->andWhere('coach.id = :coach')
            ->setParameter('coach', $user)
        ;
        return $qb;
    }

    public  function findYoungster()
    {
        $qb = $this->createQueryBuilder('user')
            ->andWhere('user.role = :role ')
            ->setParameter('role', 'ROLE_YOUNGSTER')
        ;
        return $qb;
    }
}
