user_user:
    resource: "@UserBundle/Resources/config/routing/user.yml"
    prefix:   /user

user_organization:
        resource: "@UserBundle/Resources/config/routing/organization.yml"
        prefix:   /organization